//
//  ArrayCvl.swift
//  XcodeProject
//
//  Created by KEITA on 08/12/2023.
//

import Foundation
import SwiftUI

struct ClevelandTeam : Identifiable {
    var id  = UUID()
    var name : String
    var post : String
    var number : Int
    var picture : String
    var story : String
    var gamesSaison : Int
    var gamesCareer : Int
    var PPG : Double
    var RPG : Double
    var APG : Double
}

let ArrayRoster = [
    
    ClevelandTeam( name: "Donovan Michell", post: "Meneur", number: 45, picture: "donovanMichell", story: " Donovan Mitchell, né le 7 septembre 1996 à Elmsford, New York, est un talentueux joueur de basketball professionnel évoluant dans la National Basketball Association (NBA) avec l'équipe du Utah Jazz. Mitchell a connu une ascension remarquable depuis le début de sa carrière. Mitchell a fait ses débuts universitaires à l'Université de Louisville, où il a joué pour les Cardinals. Sa première saison a été particulièrement impressionnante, le propulsant sur le devant de la scène du basketball universitaire. En 2017, après seulement deux saisons universitaires, il a décidé de se présenter à la draft de la NBA. C'est lors de la draft de 2017 que Donovan Mitchell a été sélectionné en 13e position par les Denver Nuggets, mais a été immédiatement échangé avec le Utah Jazz. Cette décision s'est avérée être un tournant majeur pour lui, car il a rapidement émergé comme l'une des jeunes stars les plus prometteuses de la ligue.Sa saison rookie avec le Jazz a été époustouflante. Mitchell a fait preuve d'une incroyable habileté offensive, de qualités de meneur de jeu et d'une éthique de travail exceptionnelle. Il a joué un rôle clé dans la réussite de son équipe, atteignant même les séries éliminatoires dès sa première saison. Au fil des saisons, Donovan Mitchell a continué à s'affirmer comme l'un des meilleurs arrières de la ligue. Sa polyvalence, sa rapidité et son habileté à marquer des paniers cruciaux ont valu au Jazz de nombreuses victoires. En plus de ses compétences athlétiques, Mitchell est également loué pour son leadership sur le terrain et son engagement envers sa communauté en dehors du basketball.Le parcours de Donovan Mitchell dans la NBA continue d'évoluer, avec des attentes élevées pour l'avenir. En tant que joueur dynamique et charismatique, il ne fait aucun doute que Mitchell laissera une empreinte durable dans l'histoire du basketball professionnel.",gamesSaison:16,gamesCareer:429,PPG: 27.6,RPG: 5.4,APG: 5.3),
ClevelandTeam(name: "Jarett Allen", post: "Pivot", number: 31, picture: "jarettMichell", story: "Jarrett Allen, né le 21 avril 1998 à San Diego, en Californie, est un pivot talentueux de la National Basketball Association (NBA), actuellement en action avec les Cleveland Cavaliers. Son parcours dans le monde du basketball a été marqué par son ascension rapide et sa constante amélioration.Allen a commencé à se faire un nom pendant son passage à l'Université du Texas, où il a joué pour les Longhorns. Grâce à ses performances exceptionnelles en tant que pivot, il a attiré l'attention des recruteurs de la NBA. En 2017, Jarrett Allen a pris la décision de se présenter à la draft de la NBA après seulement une saison universitaire.Lors de la draft de 2017, Allen a été choisi en 22e position par les Brooklyn Nets. Sa taille imposante, son envergure et sa capacité à bloquer des tirs en ont fait un ajout précieux à l'équipe. Au fil des saisons avec les Nets, Allen a développé ses compétences et s'est imposé comme l'un des meilleurs jeunes pivots de la ligue.Sa capacité à protéger le cercle et à contribuer offensivement a été un atout majeur pour les Nets. Cependant, en janvier 2021, Allen a été inclus dans un échange majeur impliquant plusieurs équipes, et il a rejoint les Cleveland Cavaliers.Avec les Cavaliers, Jarrett Allen a continué à s'épanouir. Sa présence dans la raquette, combinée à sa mobilité sur le terrain, en a fait un pilier de l'équipe. En plus de son impact sur le plan statistique, Allen est également apprécié pour son éthique de travail acharnée et son attitude positive sur et en dehors du terrain.Le parcours de Jarrett Allen dans la NBA est un exemple de persévérance et de développement constant. En tant que jeune pivot prometteur, il continue de gagner en expérience et d'affirmer sa place parmi les joueurs de premier plan de la ligue. L'avenir semble prometteur pour Jarrett Allen, et les fans des Cavaliers ont certainement hâte de voir son influence grandissante dans les années à venir.",gamesSaison:16,gamesCareer:425,PPG: 13.4,RPG: 8.3,APG: 2.3),
                   
ClevelandTeam(name: "Max Strus", post: "Meneur/Arrière", number: 1, picture: "steveStrus",story: "une force montante du monde du basketball. Originaire de Hickory Hills, dans l'Illinois, Strus a tracé son chemin vers les parquets de la NBA avec une détermination inébranlable et un talent impressionnant. Max Strus s'est fait connaître lors de son passage à DePaul University, où il a attiré l'attention grâce à son jeu dynamique et sa capacité à marquer à partir de n'importe quelle position sur le terrain. Ses performances remarquables lui ont ouvert les portes de la Draft NBA, bien qu'il ait dû faire face à des défis sur son chemin vers la ligue majeure. Après avoir signé avec les Boston Celtics, Strus a commencé à faire sa marque dans la NBA avec son tir extérieur redoutable et son engagement inébranlable sur le terrain. Sa présence énergique a rapidement captivé les fans et a fait de lui un élément précieux de son équipe. Chaque tir à trois points de Strus semble porter l'essence d'un joueur déterminé à repousser ses propres limites. Son parcours professionnel est un témoignage de la persévérance et de la passion qui le motivent à exceller à chaque match.  L'histoire de Max Strus continue de se dérouler sur les parquets de la NBA, où chaque panier raconte l'histoire d'un joueur prêt à relever tous les défis pour atteindre de nouveaux sommets dans le monde du basketball.",gamesSaison:21,gamesCareer:210,PPG: 14.5,RPG: 5.5,APG: 4.1),
                   
ClevelandTeam(name: "Darius Garland", post: "Meneur", number: 10, picture: "dariusGarland", story: "Darius Garland, né le 26 janvier 2000 à Gary, Indiana, est un meneur de jeu éclatant de la National Basketball Association (NBA), évoluant avec les Cleveland Cavaliers. Son ascension rapide et son style de jeu captivant en ont fait l'une des jeunes stars montantes de la ligue.Garland a attiré l'attention pendant son passage à la Vanderbilt University, où il a joué pour les Commodores. Malgré une saison universitaire écourtée en raison d'une blessure, ses compétences en tant que meneur de jeu et sa précision au tir ont captivé les recruteurs de la NBA. En 2019, il a décidé de se présenter à la draft.Lors de la draft de 2019, Darius Garland a été choisi en 5e position par les Cleveland Cavaliers. Sa vision du jeu exceptionnelle, sa dextérité avec le ballon et sa capacité à marquer de loin ont rapidement attiré l'attention. Bien qu'il ait connu une première saison écourtée en raison de blessures, Garland a montré des éclairs de son immense potentiel.Au fil des saisons, Darius Garland a continué à s'épanouir sous le maillot des Cavaliers. Sa combinaison de compétences de passe, de maniement de balle et de tir a fait de lui le meneur de jeu incontournable de l'équipe. Garland est également reconnu pour sa capacité à prendre des responsabilités dans des moments cruciaux du match.Sa connexion sur le terrain avec Jarrett Allen a créé une dynamique prometteuse pour l'avenir des Cavaliers. En plus de ses exploits sur le terrain, Garland est apprécié pour son état d'esprit professionnel et son dévouement envers l'amélioration constante.À mesure que Darius Garland continue de mener les Cavaliers, les attentes pour sa carrière future restent élevées. Son parcours dans la NBA est un exemple de détermination et de croissance, et il est indéniable que les fans peuvent s'attendre à voir Garland jouer un rôle de plus en plus central dans le succès de son équipe au fil des saisons à venir.",gamesSaison:16,gamesCareer:266,PPG: 19.7,RPG: 2.7,APG: 6.1),
                   
ClevelandTeam(name: "Evan Mobley", post: "Pivot", number: 4, picture: "evanmobley",story: "une étoile montante du monde du basketball. Originaire de San Diego, en Californie, Mobley a tracé son chemin vers les sommets du sport grâce à son talent exceptionnel et à sa passion pour le jeu.Son périple universitaire avec les USC Trojans a été une aventure captivante. Dès le premier saut sur le parquet, Mobley a laissé sa marque avec ses compétences polyvalentes, combinant taille, agilité et intelligence de jeu. Les projecteurs se sont braqués sur lui, et il est devenu l'une des figures centrales de la Draft NBA de 2021. Les Cleveland Cavaliers ont saisi l'opportunité de faire d'Evan Mobley la pièce maîtresse de leur équipe. Sa présence sur le terrain est bien plus qu'une simple manifestation de talent brut ; c'est une fusion artistique de finesse technique et de détermination. Sur le parquet de la NBA, Mobley a continué à émerveiller les fans et les observateurs avec son jeu complet. Que ce soit en défense avec ses blocs impressionnants ou en attaque avec sa vision du jeu, il incarne la nouvelle génération de joueurs qui repoussent les limites du possible.L'histoire d'Evan Mobley est en constante évolution, chaque dribble et chaque panier ajoutant un nouveau chapitre à son récit sportif. Une chose est sûre : le voyage de Mobley promet d'être une aventure épique sur les terrains de basketball du monde entier.",gamesSaison:21,gamesCareer:169,PPG: 16.0,RPG: 10.5,APG: 2.9)

]
